CREATE TABLE SUBJECT(
	ID VARCHAR(15) PRIMARY KEY,
	NAME  VARCHAR(35) NOT NULL,
	SEMESTER INTEGER NOT NULL,
	CLASS VARCHAR(30) NOT NULL,
	PROF VARCHAR(50) NOT NULL,
	SCHEDULE VARCHAR(20) NOT NULL,
	GRADE INTEGER
);

CREATE TABLE ASSIGNMENT(
	NAME VARCHAR(30) PRIMARY KEY,
	CATEGORY VARCHAR(20) NOT NULL,
	ASSIGN_DATE DATE NOT NULL,
	DUE_DATE DATE NOT NULL,
	TURNIN_DATE DATE,
	GRADE INTEGER
);

CREATE TABLE CATEGORY(
	NAME VARCHAR(30) NOT NULL,
	SUBJECT VARCHAR(15)REFERENCES SUBJECT(ID),
	ID VARCHAR(46) NOT NULL PRIMARY KEY,
	VALUE INTEGER NOT NULL,
	FINAL_GRADE INTEGER
);

